"""Shared lake name mappings for tournament data loaders."""

LAKES = {
    "amistad": "Lake Amistad",
    "austin": "Lake Austin",
    "belton": "Lake Belton",
    "braunig": "Braunig Lake",
    "buchanan": "Lake Buchanan",
    "calaveras": "Calaveras Lake",
    "canyon": "Canyon Lake",
    "cedar creek": "Cedar Creek Reservoir",
    "choke": "Choke Canyon Reservoir",
    "coleto": "Coleto Creek Reservoir",
    "dunlap": "Lake Dunlap",
    "eagle": "Eagle Mountain Lake",
    "falcon": "Lake Falcon",
    "fork": "Lake Fork",
    "granger": "Granger Lake",
    "inks": "Inks Lake",
    "ivie": "O.H. Ivie Reservoir",
    "lady bird": "Lady Bird Lake",
    "lbj": "Lake LBJ",
    "lewisville": "Lake Lewisville",
    "limestone": "Lake Limestone",
    "marble falls": "Lake Marble Falls",
    "medina": "Medina Lake",
    "pflugerville": "Lake Pflugerville",
    "ray roberts": "Lake Ray Roberts",
    "red river": "The Red River",
    "richland": "Richland-Chambers Reservoir",
    "sabine": "The Sabine River",
    "sam rayburn": "Sam Rayburn Reservoir",
    "squaw": "Squaw Creek",
    "stillhouse": "Stillhouse Hollow Lake",
    "tawakoni": "Lake Tawakoni",
    "texoma": "Lake Texoma",
    "toledo": "Toledo Bend Reservoir",
    "travis": "Lake Travis",
    "whitney": "Lake Whitney",
}
